# Generated by Django 5.0.7 on 2024-07-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='dealerId',
            field=models.IntegerField(null=True),
        ),
    ]
