# Generated by Django 5.0.7 on 2024-07-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_carmodel_dealerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealerId',
        ),
    ]
